---
- id: psscriptanalyzer-check
  name: check PowerShell code using PSScriptAnalyzer
  language: script
  entry: pre-commit-run.sh -Check
  args:
    - -ExcludeRule
    - PSUseBOMForUnicodeEncodedFile
    - -Fix
  types:
    - file
  files: \.ps[dm]?1$

- id: psscriptanalyzer-format
  name: format PowerShell code using PSScriptAnalyzer
  language: script
  entry: pre-commit-run.sh -Format
  types:
    - file
  files: \.ps[dm]?1$

- id: psscriptanalyzer-check-docker
  name: check PowerShell code using PSScriptAnalyzer
  language: docker
  entry: -Check
  args:
    - -ExcludeRule
    - PSUseBOMForUnicodeEncodedFile
    - -Fix
  types:
    - file
  files: \.ps[dm]?1$

- id: psscriptanalyzer-format-docker
  name: format PowerShell code using PSScriptAnalyzer
  language: docker
  entry: -Format
  types:
    - file
  files: \.ps[dm]?1$
